### ISSUE TITLE
Can't spawn() after interact()

### ISSUE THREAD

**Issue by GaryBoone** [zhiburt/expectrl#7] opened 2021-07-22 00:11 UTC
Running another `spawn()` after calling `interact()` causes the spawn to fail with a `Sys(EBADF)` error. 

If the repro code below is run _without_ the `interact()` function, it calls `spawn()` and prints the process info as expected:

    Running PtyProcess { master: Master { fd: PtyMaster(7) }, child_pid: Pid(97435), stream: 
    Stream { inner: File { fd: 9, path: "/dev/ptmx", read: true, write: true }, reader: BufReader { 
    reader: Reader { inner: File { fd: 10, path: "/dev/ptmx", read: true, write: true } }, buffer: 0/8192 
    } }, eof_char: 4, intr_char: 3, terminate_approach_delay: 100ms }

However, if the `interact()` function _is_ called, the subsequent call to `spawn()` fails:

    Cargo.lock	Cargo.toml	src		target
    Quiting status Exited(Pid(96414), 0)
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sys(EBADF)', src/main.rs:20:42
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Repro code:

    use expectrl::Session;
    use ptyprocess::PtyProcess;
    use std::{process::Command, thread, time::Duration};

    fn main() {
        let cmd = Command::new("ls");
        let mut bash = Session::spawn_cmd(cmd).expect("Error while spawning bash");
        //
        // If these two lines are commented out, the spawn() below starts and the
        // process information is printed.
        //
        // If these two lines are enabled, the interact() succeeds and the exit code
        // 0 is printed, but the spawn() below panics.
        let status = bash.interact().expect("Failed to start interact");
        println!("Quiting status {:?}", status);

        // Now start another.
        thread::sleep(Duration::from_millis(500));   // Delay just in case.

        let cmd = Command::new("ls");
        let process = PtyProcess::spawn(cmd).unwrap();
        println!("Running {:?}", process);
    }

Tested on macOs.

**Comment by zhiburt** [comment] 2021-07-22 09:25
So the issue is in dropping `stdin` descriptor.

Possible resolution is not to drop cloned descriptor using `std::mem::forget` or use `dup`.

Honestly I was thinking that `std::fs::File::try_clone` does exactly `dup` but it's not. Eventhough it uses a different descriptor closing it causes an original descriptor be closed as well. Which is kind of undocumented I guess?

You can see it in this example.

```rust
use std::{
    os::unix::prelude::{AsRawFd, FromRawFd},
};

fn open_fds() {
    let fds = std::fs::read_dir(format!("/proc/{}/fd", std::process::id()))
        .unwrap()
        .flatten()
        .map(|s| s.file_name())
        .collect::<Vec<_>>();
    println!("{:?}", fds);
}

fn main() {
    open_fds();

    let mut buf = String::new();
    std::io::stdin().read_line(&mut buf).unwrap();

    let fd = std::io::stdin().as_raw_fd();
    println!("stdin = {:?}", fd);
    let stdin = unsafe { std::fs::File::from_raw_fd(fd).try_clone().unwrap() };
    println!("new_stdin = {:?}", stdin.as_raw_fd());
    let stdin_stream = ptyprocess::stream::Stream::new(stdin);

    open_fds();

    std::io::stdin().read_line(&mut buf).unwrap();

    drop(stdin_stream);

    let fd = std::io::stdin().as_raw_fd();
    println!("stdin = {:?}", fd);

    open_fds();

    let a = std::io::stdin().read_line(&mut buf).unwrap();

    println!("aaa {}", a);
}
```

**Comment by zhiburt** [comment] 2021-07-22 09:26
Funny to say that because I think that `dup` stuff is relatively low level the interact function shall be moved back to `ptyprocess` I guess.

**Comment by zhiburt** [comment] 2021-07-22 09:26
By the way @GaryBoone good catch ! :sweat_smile:

**Comment by zhiburt** [comment] 2021-07-22 09:31
This is a `std` implementation

https://doc.rust-lang.org/src/std/sys/unix/fd.rs.html

```rust
    pub fn duplicate(&self) -> io::Result<FileDesc> {
        // We want to atomically duplicate this file descriptor and set the
        // CLOEXEC flag, and currently that's done via F_DUPFD_CLOEXEC. This
        // is a POSIX flag that was added to Linux in 2.6.24.
        let fd = cvt(unsafe { libc::fcntl(self.raw(), libc::F_DUPFD_CLOEXEC, 0) })?;
        Ok(FileDesc::new(fd))
    }
```

**Comment by zhiburt** [comment] 2021-07-22 09:49
By the way as I understand I isn't explicitly said that it works this way.

```rfc
       F_DUPFD_CLOEXEC (int; since Linux 2.6.24)
              As for F_DUPFD, but additionally set the close-on-exec
              flag for the duplicate file descriptor.  Specifying this
              flag permits a program to avoid an additional fcntl()
              F_SETFD operation to set the FD_CLOEXEC flag.  For an
              explanation of why this flag is useful, see the
              description of O_CLOEXEC in open(2).
```

```rfc
       O_CLOEXEC (since Linux 2.6.23)
              Enable the close-on-exec flag for the new file descriptor.
              Specifying this flag permits a program to avoid additional
              fcntl(2) F_SETFD operations to set the FD_CLOEXEC flag.

              Note that the use of this flag is essential in some
              multithreaded programs, because using a separate fcntl(2)
              F_SETFD operation to set the FD_CLOEXEC flag does not
              suffice to avoid race conditions where one thread opens a
              file descriptor and attempts to set its close-on-exec flag
              using fcntl(2) at the same time as another thread does a
              fork(2) plus execve(2).  Depending on the order of
              execution, the race may lead to the file descriptor
              returned by open() being unintentionally leaked to the
              program executed by the child process created by fork(2).
              (This kind of race is in principle possible for any system
              call that creates a file descriptor whose close-on-exec
              flag should be set, and various other Linux system calls
              provide an equivalent of the O_CLOEXEC flag to deal with
              this problem.)
``` 

# issue

Here's an 2 examples which I would assume work in the same way but they aren't.

```rust
fn main() {
    // STDIN works
    let mut buf = String::new();
    std::io::stdin().read_line(&mut buf).unwrap();

    // doing F_DUPFD_CLOEXEC
    let stdin = unsafe { std::fs::File::from_raw_fd(0).try_clone().unwrap() };
    
    // STDIN works
    std::io::stdin().read_line(&mut buf).unwrap();

    // drop dupped stdin
    drop(stdin);

    // STDIN doesn't work
    std::io::stdin().read_line(&mut buf).unwrap();

}
```

```rust

fn main() {
    // STDIN works
    let mut buf = String::new();
    std::io::stdin().read_line(&mut buf).unwrap();

    // doing F_DUPFD_CLOEXEC
    let new_stdin = nix::unistd::dup(0).unwrap();
    let stdin = unsafe { std::fs::File::from_raw_fd(new_stdin) };

    // STDIN works
    std::io::stdin().read_line(&mut buf).unwrap();

    // drop dupped stdin
    drop(stdin);

    // STDIN works
    std::io::stdin().read_line(&mut buf).unwrap();
}
```

**Comment by zhiburt** [comment] 2021-07-22 09:50
@GaryBoone do you have any idea?

**Comment by zhiburt** [comment] 2021-07-22 11:25
So I fixed it.

I'll bump version of crates.io later today.

**Comment by GaryBoone** [comment] 2021-07-22 20:08
Confirmed working, so closing bug. Thanks!

**Closed** 2021-07-22 20:09 UTC
